
# This file was *autogenerated* from the file sagemath_scripts/test.sage
from sage.all_cmdline import *   # import sage library

_sage_const_0x7CA110454A1A6E57 = Integer(0x7CA110454A1A6E57); _sage_const_0x01A1D6D039776742 = Integer(0x01A1D6D039776742)
from sage.crypto.block_cipher.des import DES

des = DES()
P = _sage_const_0x01A1D6D039776742 
K = _sage_const_0x7CA110454A1A6E57 
C = des.encrypt(plaintext=P, key=K)
print(c.hex())
P = des.decrypt(ciphertext=C, key=K)
print(P.hex())

